require('./db')
const express = require('express')
const cors = require('cors')
const bodyParser = require('body-parser')
var handleDataRoute = require('./controllers/postDataController')
var app = express()
app.use(bodyParser.json())
app.use(cors())
app.listen(4000,()=>console.log('Server started at port 4000'))
app.use('/dataHandle',handleDataRoute)